#!/usr/bin/env bash

echo "INFO: Kill any running wetap virtual machines."
VBoxManage list runningvms | grep wetap | cut -f1 -d " "| sed 's/"//g' | while read machine_uuid; do VBoxManage controlvm $machine_uuid poweroff; done

vagrant box update
vagrant up --provision

vagrant ssh << END
who -a
uname -a
cd /vagrant

bundle exec rake db:test:prepare
script/ci-rspec &&
script/ci-cucumber
END

BUILD_SUCCESS=$?

# Halt VM to avoid conflicts with other builds
vagrant halt
exit $BUILD_SUCCESS
