#!/usr/bin/env bash

vagrant halt
vagrant box update
vagrant up --provision

vagrant ssh << END
who -a
uname -a
cd /vagrant

bundle exec rake db:test:prepare
script/ci-rspec &&
script/ci-cucumber
END

BUILD_SUCCESS=$?

# Halt VM to avoid conflicts with other builds
vagrant halt
exit $BUILD_SUCCESS
