#!/bin/sh
# fetches remote DB and overwrites local with its contents
# usage: script/db_pull wetap
# defaults to staging

set -e

APP=${1:-wetap-staging}
DATABASE_NAME=wetap-api_development
DUMP_NAME=tmp/$APP.dump
MY_DIR=`dirname $0`

echo dumping latest $APP db into local $DATABASE_NAME

heroku pg:backups capture --app $APP
curl -o $DUMP_NAME `heroku pgbackups:url --app $APP`

$MY_DIR/db_load $APP
