require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WaterFountainsController do

  # This should return the minimal set of attributes required to create a valid
  # WaterFountain. As you add validations to WaterFountain, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "location" => {"type" => "Point","coordinates" => [1.0,1.0]} } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WaterFountainsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all water_fountains as @water_fountains" do
      water_fountain = WaterFountain.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:water_fountains)).to eq([water_fountain])
    end
  end

  describe "GET show" do
    it "assigns the requested water_fountain as @water_fountain" do
      water_fountain = WaterFountain.create! valid_attributes
      get :show, {:id => water_fountain.to_param}, valid_session
      expect(assigns(:water_fountain)).to eq(water_fountain)
    end
  end

  describe "GET new" do
    it "assigns a new water_fountain as @water_fountain" do
      get :new, {}, valid_session
      expect(assigns(:water_fountain)).to be_a_new(WaterFountain)
    end
  end

  describe "GET edit" do
    it "assigns the requested water_fountain as @water_fountain" do
      water_fountain = WaterFountain.create! valid_attributes
      get :edit, {:id => water_fountain.to_param}, valid_session
      expect(assigns(:water_fountain)).to eq(water_fountain)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new WaterFountain" do
        expect {
          post :create, {:water_fountain => valid_attributes}, valid_session
        }.to change(WaterFountain, :count).by(1)
      end

      it "assigns a newly created water_fountain as @water_fountain" do
        post :create, {:water_fountain => valid_attributes}, valid_session
        expect(assigns(:water_fountain)).to be_a(WaterFountain)
        expect(assigns(:water_fountain)).to be_persisted
      end

      it "redirects to the created water_fountain" do
        post :create, {:water_fountain => valid_attributes}, valid_session
        expect(response).to redirect_to(WaterFountain.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved water_fountain as @water_fountain" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(WaterFountain).to receive(:save).and_return(false)
        post :create, {:water_fountain => { "location" => "invalid value" }}, valid_session
        expect(assigns(:water_fountain)).to be_a_new(WaterFountain)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(WaterFountain).to receive(:save).and_return(false)
        post :create, {:water_fountain => { "location" => "invalid value" }}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested water_fountain" do
        water_fountain = WaterFountain.create! valid_attributes
        # Assuming there are no other water_fountains in the database, this
        # specifies that the WaterFountain created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(WaterFountain).to receive(:update).with({ "location" => "" })
        put :update, {:id => water_fountain.to_param, :water_fountain => { "location" => "" }}, valid_session
      end

      it "assigns the requested water_fountain as @water_fountain" do
        water_fountain = WaterFountain.create! valid_attributes
        put :update, {:id => water_fountain.to_param, :water_fountain => valid_attributes}, valid_session
        expect(assigns(:water_fountain)).to eq(water_fountain)
      end

      it "redirects to the water_fountain" do
        water_fountain = WaterFountain.create! valid_attributes
        put :update, {:id => water_fountain.to_param, :water_fountain => valid_attributes}, valid_session
        expect(response).to redirect_to(water_fountain)
      end
    end

    describe "with invalid params" do
      it "assigns the water_fountain as @water_fountain" do
        water_fountain = WaterFountain.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(WaterFountain).to receive(:save).and_return(false)
        put :update, {:id => water_fountain.to_param, :water_fountain => { "location" => "invalid value" }}, valid_session
        expect(assigns(:water_fountain)).to eq(water_fountain)
      end

      it "re-renders the 'edit' template" do
        water_fountain = WaterFountain.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(WaterFountain).to receive(:save).and_return(false)
        put :update, {:id => water_fountain.to_param, :water_fountain => { "location" => "invalid value" }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested water_fountain" do
      water_fountain = WaterFountain.create! valid_attributes
      expect {
        delete :destroy, {:id => water_fountain.to_param}, valid_session
      }.to change(WaterFountain, :count).by(-1)
    end

    it "redirects to the water_fountains list" do
      water_fountain = WaterFountain.create! valid_attributes
      delete :destroy, {:id => water_fountain.to_param}, valid_session
      expect(response).to redirect_to(water_fountains_url)
    end
  end

end
